name: Read file contents

on: 
  workflow_dispatch:

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./myFile.json

      - name: Echo myFile.json
        run: echo "${{ steps.package.outputs.content }}"
        

